-- MySQL Script generated by MySQL Workbench
-- Thu Feb 26 09:41:53 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Calendar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Calendar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Calendar` DEFAULT CHARACTER SET utf8 ;
USE `Calendar` ;

-- -----------------------------------------------------
-- Table `Calendar`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calendar`.`USER` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `pswd` VARCHAR(45) NOT NULL,
  `fullName` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Calendar`.`ROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calendar`.`ROOM` (
  `roomID` INT NOT NULL AUTO_INCREMENT,
  `roomName` VARCHAR(45) NOT NULL,
  `capacaty` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roomID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Calendar`.`USERGROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calendar`.`USERGROUP` (
  `usergroupID` INT NOT NULL AUTO_INCREMENT,
  `isPrivate` TINYINT(1) NOT NULL,
  `USERGROUP_usergroupID` INT NULL,
  INDEX `fk_USERGROUP_USERGROUP1_idx` (`USERGROUP_usergroupID` ASC),
  PRIMARY KEY (`usergroupID`),
  CONSTRAINT `fk_USERGROUP_USERGROUP1`
    FOREIGN KEY (`USERGROUP_usergroupID`)
    REFERENCES `Calendar`.`USERGROUP` (`usergroupID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Calendar`.`APPOINTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calendar`.`APPOINTMENT` (
  `appointmentID` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `timeFrom` DATETIME NOT NULL,
  `timeTo` DATETIME NOT NULL,
  `place` VARCHAR(10) NULL,
  `type` VARCHAR(45) NULL,
  `ROOM_roomID` INT NULL,
  `USERGROUP_usergroupID` INT NULL,
  PRIMARY KEY (`appointmentID`),
  INDEX `fk_APPOINTMENT_USERGROUP1_idx` (`USERGROUP_usergroupID` ASC),
  INDEX `fk_APPOINTMENT_ROOM1_idx` (`ROOM_roomID` ASC),
  CONSTRAINT `fk_APPOINTMENT_ROOM1`
    FOREIGN KEY (`ROOM_roomID`)
    REFERENCES `Calendar`.`ROOM` (`roomID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_APPOINTMENT_USERGROUP1`
    FOREIGN KEY (`USERGROUP_usergroupID`)
    REFERENCES `Calendar`.`USERGROUP` (`usergroupID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Calendar`.`USER_has_USERGROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calendar`.`USER_has_USERGROUP` (
  `groupAdmin` TINYINT(1) NOT NULL,
  `USER_userID` INT NOT NULL,
  `USERGROUP_usergroupID` INT NOT NULL,
  PRIMARY KEY (`USER_userID`, `USERGROUP_usergroupID`),
  INDEX `fk_USER_has_USERGROUP_USERGROUP1_idx` (`USERGROUP_usergroupID` ASC),
  CONSTRAINT `fk_USER_has_USERGROUP_USER1`
    FOREIGN KEY (`USER_userID`)
    REFERENCES `Calendar`.`USER` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USER_has_USERGROUP_USERGROUP1`
    FOREIGN KEY (`USERGROUP_usergroupID`)
    REFERENCES `Calendar`.`USERGROUP` (`usergroupID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Calendar`.`ADMINS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calendar`.`ADMINS` (
  `USER_userID` INT NOT NULL,
  `APPOINTMENT_appointmentID` INT NOT NULL,
  PRIMARY KEY (`USER_userID`, `APPOINTMENT_appointmentID`),
  INDEX `fk_USER_has_APPOINTMENT_APPOINTMENT3_idx` (`APPOINTMENT_appointmentID` ASC),
  CONSTRAINT `fk_USER_has_APPOINTMENT_USER3`
    FOREIGN KEY (`USER_userID`)
    REFERENCES `Calendar`.`USER` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USER_has_APPOINTMENT_APPOINTMENT3`
    FOREIGN KEY (`APPOINTMENT_appointmentID`)
    REFERENCES `Calendar`.`APPOINTMENT` (`appointmentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Calendar`.`INVITATIONSTATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calendar`.`INVITATIONSTATUS` (
  `status` CHAR(1) NOT NULL,
  `USER_userID` INT NOT NULL,
  `APPOINTMENT_appointmentID` INT NOT NULL,
  PRIMARY KEY (`USER_userID`, `APPOINTMENT_appointmentID`),
  INDEX `fk_USER_has_APPOINTMENT_APPOINTMENT2_idx` (`APPOINTMENT_appointmentID` ASC),
  CONSTRAINT `fk_USER_has_APPOINTMENT_USER2`
    FOREIGN KEY (`USER_userID`)
    REFERENCES `Calendar`.`USER` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USER_has_APPOINTMENT_APPOINTMENT2`
    FOREIGN KEY (`APPOINTMENT_appointmentID`)
    REFERENCES `Calendar`.`APPOINTMENT` (`appointmentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Calendar`.`ALARM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calendar`.`ALARM` (
  `alarmID` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `USER_userID` INT NOT NULL,
  `APPOINTMENT_appointmentID` INT NOT NULL,
  PRIMARY KEY (`alarmID`, `USER_userID`, `APPOINTMENT_appointmentID`),
  INDEX `fk_ALARM_USER1_idx` (`USER_userID` ASC),
  INDEX `fk_ALARM_APPOINTMENT1_idx` (`APPOINTMENT_appointmentID` ASC),
  CONSTRAINT `fk_ALARM_USER1`
    FOREIGN KEY (`USER_userID`)
    REFERENCES `Calendar`.`USER` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ALARM_APPOINTMENT1`
    FOREIGN KEY (`APPOINTMENT_appointmentID`)
    REFERENCES `Calendar`.`APPOINTMENT` (`appointmentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
